name: 24h全天候保活服务

on:
  schedule:
    # 每 30 分钟敲一次门
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  wake_up:
    runs-on: ubuntu-latest
    steps:
      - name: 模拟真人访问
        #末尾的 || exit 0 是关键，它会强制让任务显示为绿色成功，停止发送报错邮件
        run: |
          curl -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" \
               -L https://policy-search-vk.streamlit.app/ || exit 0
